<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite841c0a8d340fd2ab1b62f88d49eae42
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite841c0a8d340fd2ab1b62f88d49eae42::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite841c0a8d340fd2ab1b62f88d49eae42::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite841c0a8d340fd2ab1b62f88d49eae42::$classMap;

        }, null, ClassLoader::class);
    }
}
